name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.emacs_version == 'snapshot' }}

    strategy:
      matrix:
        emacs_version:
        - 29.1
        - snapshot

    steps:
      - uses: actions/checkout@v3

      - name: Install build tools
        run: |
          sudo apt-get install build-essential -y

      - name: Setup emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Install Eldev
        uses: emacs-eldev/setup-eldev@v1

      - name: Install nushell language grammar
        run: |
          eldev -dtT -C eval -R "
              (progn
              (require 'treesit)
              (add-to-list 'treesit-language-source-alist
                  '(nu \"https://github.com/nushell/tree-sitter-nu\"))
              (treesit-install-language-grammar 'nu))
          "
      - name: Test the project
        run: |
          eldev -p -dtT -C test

      - name: Ensure there are no byte-compilation warnings
        run: |
          eldev -dtT -C compile --set all --warnings-as-errors

      - name: Lint the project
        run: |
          eldev -p -dtT -C lint
